### ISSUE TITLE
Fix Update of user (creating new one for now)

### ISSUE THREAD

**Issue by Fredohm** [Fredohm/springbootintranet#99]

**Comment by TortueDeBois** [comment]
To find the root issue, I tried this with Postman:
![image](https://user-images.githubusercontent.com/43149177/121513915-ad7bc780-c9eb-11eb-85af-77acb995aa5f.png)

By Adding this ouput in [UserRestServiceImpl](https://github.com/Fredohm/springbootintranet/blob/master/springbootintranet-data/src/main/java/org/fredohm/springbootintranet/services/api/v1/impl/UserRestServiceImpl.java):
![image](https://user-images.githubusercontent.com/43149177/121514041-da2fdf00-c9eb-11eb-976b-54e823ac8369.png)
I receive these messages:
![image](https://user-images.githubusercontent.com/43149177/121514319-2a0ea600-c9ec-11eb-96b8-4082b0b83661.png)

Currently, I only find that UserMapperImpl convert Id and version into UserDto but into User.
In result, updateUser acts like createUpdate because it received an id null.
A simple but not satisfying fix will be try.
